# Site settings
title: "First Order"
description: "The First Order exists to eliminate chaos and corruption, to reclaim the Imperial legacy and to restore stability to the galaxy."
url: "https://yiu.co.uk/starwars"
permalink: pretty

# Account settings
twitter: clry2
facebook: 509241123
ga4: G-7CHPEC8W2F

# Build settings
markdown: kramdown
sass:
  sourcemap: never